# Generated by Django 5.1 on 2024-08-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggenerator', '0002_blogpost_transcript_alter_blogpost_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='transcript',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='youtube_link',
            field=models.CharField(max_length=300),
        ),
    ]
