# Generated by Django 5.1 on 2024-08-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggenerator', '0003_alter_blogpost_transcript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='youtube_link',
            field=models.URLField(),
        ),
    ]
